# Generated by Django 2.2.6 on 2019-10-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('name', models.CharField(help_text='Enter school_name', max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
