# Generated by Django 2.2.6 on 2019-10-17 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0003_auto_20191016_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailurl',
            name='URL',
            field=models.URLField(help_text='Enter school email url', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter class name', max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('professor_name', models.CharField(help_text='Enter professor name', max_length=255)),
                ('class_info', models.TextField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamapp.School')),
            ],
            options={
                'unique_together': {('name', 'school', 'start_time', 'end_time', 'professor_name')},
            },
        ),
    ]
