# Generated by Django 2.2.6 on 2019-10-17 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teamapp', '0004_auto_20191017_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middlename', models.CharField(blank=True, max_length=255, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamapp.School')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('team_info', models.TextField()),
                ('max_teammates', models.IntegerField()),
                ('in_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamapp.Class')),
            ],
            options={
                'unique_together': {('in_class', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamapp.Student')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamapp.Team')),
            ],
            options={
                'unique_together': {('student', 'team')},
            },
        ),
        migrations.CreateModel(
            name='EnrolledIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamapp.School')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamapp.Student')),
            ],
            options={
                'unique_together': {('student', 'school')},
            },
        ),
    ]
