# Generated by Django 2.2.6 on 2019-10-17 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0006_auto_20191017_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='middlename',
            new_name='middle_name',
        ),
    ]
