# Generated by Django 2.2.6 on 2019-10-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0007_auto_20191017_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
