# Generated by Django 2.2.6 on 2019-10-17 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0008_auto_20191017_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledin',
            name='in_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teamapp.Class'),
        ),
        migrations.AlterUniqueTogether(
            name='enrolledin',
            unique_together={('student', 'in_class')},
        ),
        migrations.RemoveField(
            model_name='enrolledin',
            name='school',
        ),
    ]
