# Generated by Django 2.2.6 on 2019-10-17 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0009_auto_20191017_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledin',
            name='in_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamapp.Class'),
        ),
    ]
