# Generated by Django 2.2.6 on 2019-10-20 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0010_auto_20191017_0114'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('name', 'school', 'professor_name')},
        ),
        migrations.RemoveField(
            model_name='class',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='class',
            name='start_time',
        ),
    ]
