# Generated by Django 2.2.6 on 2019-11-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0013_team_team_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_image',
            field=models.ImageField(blank=True, upload_to='team_image'),
        ),
    ]
