# Generated by Django 2.2.6 on 2019-11-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0014_team_team_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_image',
            field=models.ImageField(blank=True, upload_to='student_image'),
        ),
    ]
