# Generated by Django 2.2.6 on 2019-10-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0005_enrolledin_student_team_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='middlename',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
